[package]
name = "day-12a"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.76"
cached = "0.46.1"
itertools = "0.12.0"
once_cell = "*"
regex = "1.10.2"
strum_macros = "*"
